spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 10MB
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 5000
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wuli.badminton.pojo

jwt:
  secret: "hellowolrd"
  expiration: 86400000 # 24小时

file:
  upload:
    path: D:\\picture\\avatars\\
  avatar:
    url: http://localhost:8080/uploads/avatars/